#!/usr/bin/env bash
# script displays information about subdomains

if [ $# -eq 0 ];
then
	exit
fi

servers=("www" "lb-01" "web-01" "web-02")

if [ "$2" ]
then
	servers=("$2")
fi

for i in "${servers[@]}"
do
	sub="$(dig "$i"."$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $1}' | cut -d '.' -f1)"
	rec="$(dig "$i"."$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $4}')"
	dest="$(dig "$i"."$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $5}')"
	echo "The subdomain $sub is a $rec record and points to $dest"
done
