#!/usr/bin/env bash
# installs nginx web server & returns page containing a string

# update dependencies & install nginx
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx

#starts nginx web server
sudo service nginx start

string_file=/var/www/html/index.nginx-debian.html

sudo bash -c "echo 'Hello World!' > $string_file"
