#!/usr/bin/env bash
# configures nginx server to redirect to another page

# update dependencies & install nginx
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx

#starts nginx web server
sudo service nginx start

string_file=/var/www/html/index.nginx-debian.html

sudo bash -c "echo 'Hello World!' > $string_file"

new_string="server_name _;\n\n\trewrite \^\/redirect_me https:\/\/www.youtube.com\/watch\?v=QH2-TGUlwu4 permanent;/"

sudo sed -i "s/server_name _;\$/$new_string" /etc/nginx/sites-available/default
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
