#!/usr/bin/env bash
# script sets up custom header on web servers

# update dependencies & install nginx
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx

file="/etc/nginx/sites-available/default"
sudo sed -i  "21i add_header X-Served-By $HOSTNAME;" $file

# restart nginx server
sudo  service nginx restart
