#!/usr/bin/env bash
# installs & configures HAproxy on nginx server

# update dependencies
sudo apt-get -y update

# install HAproxy
sudo apt-get -y install haproxy

# configures HAproxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOT
global
	daemon
	maxconn 256

defaults
	mode http
	timeout connect 5000ms
	timeout client 50000ms
	timeout server 50000ms

frontend https_front
	bind *:80
	default_backend http_back

backend http_back
	balance roundrobin
	server web-01 52.204.237.230:80 check
	server web-02 54.152.184.95:80 check

EOT

sudo haproxy -c -f /etc/haproxy/haproxy.cfg
sudo sytemctl start haproxy
sudo systemctl enable haproxy
