#!/usr/bin/env bash
# installs & configures HAproxy on nginx server

# install HAproxy
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.4
sudo apt-get -y update
sudo apt-get -y install haproxy=2.4.\*

sudo echo "ENABLED=1" >> sudo /etc/default/haproxy

# configures HAproxy
echo "
frontend smambodev.tech
   bind *:80
   option forwardfor
   default_backend my_servers

backend my_servers
   balance roundrobin
   server 345454-web-01 52.204.237.230:80 check
   server 345454-web-02 52.86.147.166:80 check
   option httpchk
   option httpclose
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy start
