#!/usr/bin/env bash
# installs & configures HAproxy on nginx server

# update dependencies
sudo apt-get -y update

# install HAproxy
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.4
sudo apt-get -y update
sudo apt-get -y install haproxy=2.4.\*

echo "ENABLED=1" > /etc/default/haproxy

# configures HAproxy
echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 345454-web-01 52.204.237.230:80 check
   server 345454-web-02 54.152.184.95:80 check
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy start
sudo service haproxy enable
