#!/usr/bin/env bash
#Script that displays a string indefinitely and another string when SIGTERM signal is received

trap "echo 'I am invincible!!!'" SIGTERM
while 'true'
do
	echo "To infinity and beyond"
	sleep 2
done
