#!/usr/bin/env bash
#Script displays "Best School" 10 times, but on 9th iteration also displays "Hi" on \n

iterator=0
while [ $iterator -ne 11 ]
do
	if [ $iterator -eq 9 ]; then
		echo "Hi"
	else
		echo "Best School"
	fi
	((iterator++))
done
