#!/usr/bin/env bash
#Script that loops from 1 to 10 and displays certain strings for certain loop iterations

i=1
while [ $i -ne 11 ]
do
	if [ $i -eq 4 ]; then
		echo "bad luck"
	elif [ $i -eq 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
